---
title: "Untitled"
author: "Carole Voulgaris"
date: "9/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load libraries}
library(tidyverse)
library(readxl)

```

# Read in individual files

```{r}
AC_proj_data <- read_csv("alex-cox-project-data.csv") %>%
  select("ID", "Name", "Year of initial milestone", 
         "Number of stations", "Project type",
         "Funding program", "City", "State", "Mode")
AM_proj_data <- read_csv("project-data-am.csv") %>%
  select("ID", "Name", "Year of initial milestone", 
         "Number of stations", "Project type",
         "Funding program", "City", "State", "Mode")
ZI_proj_data <- read_csv("Project-Data-zi.csv") %>%
  select("ID", "Name", "Year of initial milestone", 
         "Number of stations", "Project type",
         "Funding program", "City", "State", "Mode")
MW_proj_data <- read_xlsx("final_project-data_mwj.xlsx") %>%
  select("ID", "Name", "Year of initial milestone", 
         "Number of stations", "Project type",
         "Funding program", "City", "State", "Mode")
RJ_proj_data <- read_csv("RJ_project-data - Copy.csv") %>%
  select("ID", "Name", "Year of initial milestone", 
         "Number of stations", "Project type",
         "Funding program", "City", "State", "Mode")

proj_data <- rbind(AC_proj_data, AM_proj_data, ZI_proj_data, MW_proj_data, RJ_proj_data) %>%
  filter(!is.na(ID))

```


```{r}
AC_yr_data <- read_csv("alex-cox-year-data.csv")
AM_yr_data <- read_csv("year-data-am.csv")

```